### ISSUE TITLE
panic: icmp.MessageBody is not *icmp.Echo

### ISSUE THREAD

**Issue by ericyan** [ericyan/ping#1]
```
panic: interface conversion: icmp.MessageBody is *icmp.DefaultMessageBody, not *icmp.Echo

goroutine 47 [running]:
github.com/ericyan/ping.parseMessage(0x67cf, 0xc42029c000, 0x3c, 0x5dc, 0x3c)
	/home/eric/Workspace/src/github.com/ericyan/ping/pinger.go:50 +0xfaf
github.com/ericyan/ping.NewPinger.func1(0xc42026cba0)
	/home/eric/Workspace/src/github.com/ericyan/ping/pinger.go:146 +0x231
created by github.com/ericyan/ping.NewPinger
	/home/eric/Workspace/src/github.com/ericyan/ping/pinger.go:126 +0x25c
```

**Comment by ericyan** [comment]
Original headers wrapped in destination unreachable and time exceeded messages are `*icmp.DefaultMessageBody`. Therefore, we will have to parse the message ID and seq on our own.
